### ISSUE TITLE
error: no such subcommand: `tauri-bundler`

### ISSUE THREAD

**Issue by Akiyamka** [tauri-apps/realworld#2]
Tauri looks like a tool about which many are unhappy with the electron developers dreamed of, thanks for your work!

Unfortunately, the attempt to build this repository was unsuccessful.
I collected log and outlined some places that may be interesting
 
### Steps:
-  git clone https://github.com/tauri-apps/realworld.git
- cd realworld
- yarn 
- node build       

node -v: v13.8.0
yarn -v: 1.21.1
os: Fedora 31 (Workstation Edition) x86_64 v.5.4.19

### Errors:
npm ERR! cb() never called!:
- [line 86](https://gist.github.com/Akiyamka/af717f14b0a26cd3ae2cb2ff38410200#file-log-log-L86)
- [line 522](https://gist.github.com/Akiyamka/af717f14b0a26cd3ae2cb2ff38410200#file-log-log-L522)

error: no such subcommand: `tauri-bundler`:
 - [line 151](https://gist.github.com/Akiyamka/af717f14b0a26cd3ae2cb2ff38410200#file-log-log-L151)
- [line 492](https://gist.github.com/Akiyamka/af717f14b0a26cd3ae2cb2ff38410200#file-log-log-L492)

Unhandled 'error' event:
- [line 797](https://gist.github.com/Akiyamka/af717f14b0a26cd3ae2cb2ff38410200#file-log-log-L797)

Full log:
https://gist.github.com/Akiyamka/af717f14b0a26cd3ae2cb2ff38410200#file-log-log

**Comment by Laegel** [comment]
Hey @Akiyamka , thanks for your input!
As I've written in the README, the `node build` command may not work (for now) as it's cloning, installing, initializing and building about 14 different apps (so, a lot of steps for a lot of projects which is pretty CPU intensive) and it has only been tested on my environment so far (Ubuntu 18.04).
I'm going to add some more details on the README and try to fix your issue. If you have more questions, feel free to join our Discord!

**Comment by Laegel** [comment]
@Akiyamka , could you try to execute `cargo install tauri-bundler --force` then get into any app that was correctly installed and execute `yarn tauri build`?

**Comment by Akiyamka** [comment]
@Laegel  thx, that help
