### ISSUE TITLE
error: no such subcommand 'tauri-bundler'

### ISSUE THREAD

**Issue by YairLevi** [tauri-apps/realworld#3]
Tried to run "npm run tauri build" and this error happened:
![image](https://user-images.githubusercontent.com/79797419/183394014-b3e3195c-53c6-483f-ac5a-456625eaace4.png)

how can I fix this?

cargo 1.62.1
npm 7.10.0
node 16.0.0
no yarn

**Comment by FabianLars** [comment]
This project is almost 3 years old, and is pretty much no-op right now (Tauri changed wayyy to much in this timeframe). To be honest the whole team forgot that it exists and we should archive it asap imo.
So the answer to this question
> how can I fix this?

is: Not at all in the context of this repo, sorry!

Edit: Also see here https://github.com/tauri-apps/realworld/issues/2 for the very same question, but the solution shouldn't work anymore as `tauri-bundler` is not an executable anymore (again, this project does not represent Tauri at all anymore)
